version: "3.1"
services:
  database:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=portfolios"

  minio:
    image: minio/minio:latest
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: >
      /bin/sh -c "
      wget https://dl.min.io/client/mc/release/linux-amd64/mc;
      chmod +x mc;
      ./mc mb portfolios;
      ./mc policy set download portfolios;
      minio server /data
      "

  portfolio:
    build: .
    ports:
      - "8080:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://database:3306/portfolios",
          "mops.portfolios.minio.url": "http://minio:9000/"
        }'
    depends_on:
      - database
      - minio

volumes:
  minio:

  #
