# FIXME: Change and move the definitions `MYSQL_*` to `.env` file before release

version: "3.1"
services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "23306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=portfolios"
