version: "3.1"
services:
  database:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=portfolios"

  minio:
    image: minio/minio:latest
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  portfolio:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
      - minio

volumes:
  minio: