= Lernportfolios
:icons: font
:icon-set: octicon
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


== Problemstatement

Studenten können ihre eigenen Lernprozesse nur schwer nachvollziehen. Dadurch fällt es oft nicht leicht das eigene Wissen richtig einzuschätzen.

Dozenten erhalten keine Informationen über den Lernfortschritt der Studenten. Dadurch können sie nicht auf die Schwierigkeiten der Studenten eingehen.


== Wesentliche Ziele und Features

. Was sind Lernportfolios?

.. Lernportfolios sind digitale Mappen, in denen die Arbeitsprozesse von Studenten festgehalten werden.
.. Sie dienen dazu, dass Studenten über Fehler und Lernprozesse reflektieren können.
.. Sie dienen als indirektes Feedback für Dozenten.

. Wesentliche Features

.. Vorlagen sind durch Dozenten vorgebbar.
.. Einzelne Journals können aus mehreren Beiträgen bestehen und sind immer einer Veranstaltung zugeordnet.


== Hinweise zur Dokumentation

Die Dokumentation wird in einem eigenen Branch "Documentation" geschrieben. Wir arbeiten dort alle an der Dokumentation und nehmen unsere Probleme und Entscheidungen dort auf.

== How to start and use the application

The application is started by calling `start.sh` from the repository's root directory.

To access the files uploaded to the application one must add minio hostname to /etc/hosts file
127.0.0.1   minio

This is only necessary for the demo purposes and is not demandened if minio server accessible from the user's host.
