-- MySQL Script generated by MySQL Workbench
-- Do 05 Mär 2020 13:27:21 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portfolios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolios` DEFAULT CHARACTER SET utf8 ;
USE `portfolios` ;

-- -----------------------------------------------------
-- Table `portfolios`.`Journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolios`.`Journal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `groupId` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolios`.`Entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolios`.`Entry` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `journal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Entry_1_idx` (`journal_id` ASC),
  CONSTRAINT `fk_Entry_1`
    FOREIGN KEY (`journal_id`)
    REFERENCES `portfolios`.`Journal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolios`.`Subentry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolios`.`Subentry` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `attachment` VARCHAR(255) NULL,
  `entry_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Subentry_1_idx` (`entry_id` ASC),
  CONSTRAINT `fk_Subentry_1`
    FOREIGN KEY (`entry_id`)
    REFERENCES `portfolios`.`Entry` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolios`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolios`.`Account` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL,
  `roles` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolios`.`Journal_Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolios`.`Journal_Account` (
  `journal_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  INDEX `fk_Journal_Account_1_idx` (`account_id` ASC),
  PRIMARY KEY (`journal_id`, `account_id`),
  CONSTRAINT `fk_Journal_Account_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `portfolios`.`Account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Journal_Account_2`
    FOREIGN KEY (`journal_id`)
    REFERENCES `portfolios`.`Journal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
